export const BEERS_FROM_API_SUCCESS = "BEERS_FROM_API_SUCCESS";
export const BEERS_FROM_API_FAILURE = "BEERS_FROM_API_FAILURE";
export const UPDATE_RATED_BEER_SUCCESS = "UPDATE_RATED_BEER_SUCCESS";
export const UPDATE_RATED_BEER_FAILURE = "UPDATE_RATED_BEER_FAILURE";